apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cloudpollpro-rds-20260511094620589700000002
        property: username
    - secretKey: password
      remoteRef:
        key: cloudpollpro-rds-20260511094620589700000002
        property: password
    - secretKey: host
      remoteRef:
        key: cloudpollpro-rds-20260511094620589700000002
        property: host
    - secretKey: port
      remoteRef:
        key: cloudpollpro-rds-20260511094620589700000002
        property: port
    - secretKey: dbname
      remoteRef:
        key: cloudpollpro-rds-20260511094620589700000002
        property: dbname
